
name: Download and edddxtract zip file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download zip file
        run: |
         wget -O file.zip "https://mpl1.androidfilehost.com/dl/TgQ0j3N5wnknXleOsBHakg/1688349832/10620683726822057322/system_ext.img" 
         unzip file.zip
         tar -xvf AP*.tar.md5 boot.img.lz4
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: system_ext.img
          path: system_ext.img
